<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Govind G Nair">
<meta name="dcterms.date" content="2023-10-15">
<meta name="description" content="Frequentist and Bayesian Solutions to the German Tank Problem">

<title>The German Tank Problem</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-22381ab97ffb8a420d3841344730e94d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">The German Tank Problem</h1>
                  <div>
        <div class="description">
          Frequentist and Bayesian Solutions to the German Tank Problem
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Article</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">R</div>
                <div class="quarto-category">Probability</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Govind G Nair </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 15, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#history" id="toc-history" class="nav-link active" data-scroll-target="#history">History</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#problem" id="toc-problem" class="nav-link" data-scroll-target="#problem">Problem</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a>
  <ul class="collapse">
  <li><a href="#the-frequentist-approach" id="toc-the-frequentist-approach" class="nav-link" data-scroll-target="#the-frequentist-approach">The Frequentist Approach</a>
  <ul class="collapse">
  <li><a href="#estimator" id="toc-estimator" class="nav-link" data-scroll-target="#estimator">Estimator</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  <li><a href="#a-more-conservative-confidence-interval" id="toc-a-more-conservative-confidence-interval" class="nav-link" data-scroll-target="#a-more-conservative-confidence-interval">A more conservative confidence interval</a></li>
  <li><a href="#limitations-of-the-frequentist-approach" id="toc-limitations-of-the-frequentist-approach" class="nav-link" data-scroll-target="#limitations-of-the-frequentist-approach">Limitations of the Frequentist Approach</a></li>
  </ul></li>
  <li><a href="#the-bayesian-approach" id="toc-the-bayesian-approach" class="nav-link" data-scroll-target="#the-bayesian-approach">The Bayesian Approach</a></li>
  <li><a href="#run-models" id="toc-run-models" class="nav-link" data-scroll-target="#run-models">Run Models</a>
  <ul class="collapse">
  <li><a href="#model-0---end-of-war-with-limited-intelligence" id="toc-model-0---end-of-war-with-limited-intelligence" class="nav-link" data-scroll-target="#model-0---end-of-war-with-limited-intelligence">Model 0 - End of War with limited intelligence</a></li>
  <li><a href="#model-1---beginning-of-war-with-limited-intelligence" id="toc-model-1---beginning-of-war-with-limited-intelligence" class="nav-link" data-scroll-target="#model-1---beginning-of-war-with-limited-intelligence">Model 1 - Beginning of war with limited intelligence</a></li>
  <li><a href="#model-2---end-of-war-with-superior-intelligence" id="toc-model-2---end-of-war-with-superior-intelligence" class="nav-link" data-scroll-target="#model-2---end-of-war-with-superior-intelligence">Model 2 - End of war with superior intelligence</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading">References and Further Reading</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="history" class="level1">
<h1>History</h1>
<p>Towards the end of World War II, the Germans introduced the Panther V, a successor to the Panther III and Panther IV models.Ahead of the Normandy invasion,the Allies wanted to estimate how many of these tanks they might encounter during battle. The only information they had to estimate this was the serial number of the parts of tanks they had captured or destroyed.</p>
<p>Based on just this information, Allied statisticians provided remarkably accurate estimates of German tank production as confirmed from documents captured at the end of the war.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="figure">
<p><img src="./image1.png" alt=" Comparison of Estimates and Actual Figures"></p>
<p class="caption">
</p><p>Figure 1: Comparison of Estimates and Actual Figures</p>
<p></p>
</div>
<p>This post attempts to present a solution to this problem using both frequentist and bayesian approaches.</p>
</section>
<section id="assumptions" class="level1">
<h1>Assumptions</h1>
<ol type="1">
<li><p>The tanks are numbered sequentially. i.e.&nbsp;if the first tank was numbered <span class="math inline">\(n\)</span> ,the second tank would be numbered <span class="math inline">\(n+1\)</span>.</p></li>
<li><p>Each tank encountered can come from anywhere in the sequence.</p></li>
</ol>
</section>
<section id="problem" class="level1">
<h1>Problem</h1>
<p>Given the above assumptions and re-labeling the tank numbers to start from 1, the problem can be re-stated as follows:</p>
<p><strong>Given a collection of <span class="math inline">\(k\)</span> integers, <span class="math inline">\(n_1,\dots,n_k\)</span> sampled independently and uniformly from the range <span class="math inline">\(1\)</span> to <span class="math inline">\(N\)</span>, what is the value of <span class="math inline">\(N\)</span> ?</strong></p>
</section>
<section id="model" class="level1">
<h1>Model</h1>
<p>The first step is to write down a model that gives the likelihood of observing some sequence of numbers when the parameter of interest <span class="math inline">\(N\)</span> takes a particular value. This is the likelihood function. In this case, the likelihood of observing any one tank is given by</p>
<p><span class="math display">\[ \begin{equation} P[n_1  | N = \textbf{n}] =  {\frac{1}{n}}  , for\ \textbf{1} \leq n_1 \leq \textbf{n} \end{equation} \]</span></p>
<p>The likelihood of observing a given sequence of tanks is given by:</p>
<p><span class="math display">\[ \begin{equation} P[n_1 \dots n_k | N = \textbf{n}] =  \big( {\frac{1}{n}}^k \big) , for\ \textbf{1} \leq n_1, \dots,n_k \leq \textbf{n} \end{equation} \]</span></p>
<p>This captures the idea that each number in the sequence is equally likely and the samples are independent.</p>
<section id="the-frequentist-approach" class="level2">
<h2 class="anchored" data-anchor-id="the-frequentist-approach">The Frequentist Approach</h2>
<section id="estimator" class="level3">
<h3 class="anchored" data-anchor-id="estimator">Estimator</h3>
<p>A statistic is a function that maps a sample of data to a single number, it is a quantity derived from the data. An estimator is a statistic used to estimate a population parameter. For example, if we want to estimate the mean of a population from a sample, the sample mean and the median are valid estimators.</p>
<p>For the German tank problem, a good estimator turns out to be<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>:</p>
<p><span class="math display">\[ \hat{N} = m \cdot \frac{k+1}{k} - 1  \]</span></p>
<p>where <span class="math inline">\(m = Max(n_1,\dots,n_k)\)</span></p>
<p>A good way to sanity check this estimator is by evaluating the boundary conditions.</p>
<ul>
<li><p>If you observe only one tank, <span class="math inline">\(k =1\)</span>, with a serial number <span class="math inline">\(n_1\)</span>, then <span class="math inline">\(\hat{N} = 2n_1 -1\)</span>. i.e.&nbsp;the total number of tanks is double the serial number you observed,which makes sense, since you are more likely to observe a tank near the mean of the distribution.</p></li>
<li><p>If you observe all the tanks, <span class="math inline">\(k = N\)</span>, with the maximum serial number of <span class="math inline">\(n_N\)</span> which is same as <span class="math inline">\(N\)</span>,then <span class="math inline">\(\hat{N} = N \cdot \frac{N+1}{N} - 1 = N\)</span>. This means the estimate is again correct.</p></li>
</ul>
<p>Let the tank numbers observed be 324,167,129 and 418.Then the estimated number of tanks are:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">324</span>,<span class="dv">167</span>,<span class="dv">129</span>,<span class="dv">418</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(obs)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>max_ <span class="ot">&lt;-</span> <span class="fu">max</span>(obs)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>max_<span class="sc">*</span>((k<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span>k) <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [1] 521.5</code></pre>
<p>This estimator also has the nice property of being the <strong>Minimum Variance Unbiased Estimator</strong>. In the below two sections, I take a quick detour to understand what these term means. Feel free to skip over these sections.</p>
<section id="unbiased-estimator" class="level4">
<h4 class="anchored" data-anchor-id="unbiased-estimator">Unbiased Estimator</h4>
<p>If an estimator is unbiased, the expectation or expected value of the estimator equals the true value of the parameter.</p>
<p>Let <span class="math inline">\(t_n\)</span> be an estimator at a given sample size <span class="math inline">\(n\)</span> of the true parameter <span class="math inline">\(\theta\)</span>. If the estimator is unbiased</p>
<p><span class="math display">\[ E[t_n] = \theta \]</span> It may be easier to illustrate this idea by considering Variance. Now, Variance is a measure of dispersion that almost everyone is familiar with. It is given by :</p>
<p><span class="math display">\[ Var(X) = \frac{1}{n} \sum_{i=1}^{n}(x_i - \mu)^2   \]</span></p>
<p>Despite the above definition of variance, the unbiased estimate of variance is given by.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p><span class="math display">\[\hat{Var(X)} = \frac{1}{n - 1} \sum_{i=1}^{n}(x_i - \mu)^2 \]</span> Consider a population given by <span class="math inline">\(N(0,1)\)</span>. i.e.&nbsp;a Normal Distribution with mean = 0 and variance = 1.</p>
<p>We will evaluate both formulations of variances, the one that has an expected value equal to the true variance (=1) is the unbiased sample variance.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Take 1000 draws of size 10 from the population</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate both version of variance</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>var_ <span class="ot">&lt;-</span> <span class="cf">function</span>(s){</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(s)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(s)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  var_unbiased <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>(n<span class="dv">-1</span>)<span class="sc">*</span><span class="fu">sum</span>((s <span class="sc">-</span> mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  var_biased <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>(n)<span class="sc">*</span><span class="fu">sum</span>((s <span class="sc">-</span> mean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(<span class="st">"var_unbiased"</span> <span class="ot">=</span> var_unbiased,<span class="st">"var_biased"</span> <span class="ot">=</span> var_biased))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate sample variances</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>variances <span class="ot">&lt;-</span> <span class="fu">apply</span>(samples,<span class="dv">2</span>,var_)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate expected value of both sampling distributions</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>variances_expected <span class="ot">&lt;-</span> <span class="fu">apply</span>(variances,<span class="dv">1</span>,mean)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>variances_expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## var_unbiased   var_biased 
##    0.9952352    0.8957116</code></pre>
<p>As you can see the unbiased sample variance is much closer to the true variance than the biased sample variance.</p>
</section>
<section id="minimum-variance" class="level4">
<h4 class="anchored" data-anchor-id="minimum-variance">Minimum Variance</h4>
<p>A minimum variance unbiased estimator is guaranteed to have the lowest possible variance among all unbiased estimators.</p>
<p>Consider the sample mean and the sample median. Both are unbiased estimators of the population mean.</p>
<p>Again, consider a population given by <span class="math inline">\(N(0,1)\)</span>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Take 1000 draws of size 10 from the population</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate  mean and median</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="cf">function</span>(s){</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  mean_ <span class="ot">&lt;-</span> <span class="fu">mean</span>(s)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  median_ <span class="ot">&lt;-</span> <span class="fu">median</span>(s)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean_,<span class="st">"median"</span> <span class="ot">=</span> median_))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate sample means and sample medians</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>ms <span class="ot">&lt;-</span> <span class="fu">apply</span>(samples,<span class="dv">2</span>,m)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate expected value of both sampling distributions</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>ms_expected <span class="ot">&lt;-</span> <span class="fu">apply</span>(ms,<span class="dv">1</span>,mean)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>ms_expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##        mean      median 
## 0.001409647 0.003353574</code></pre>
<p>We see that both are fairly close to the population mean. But if we evaluate the variance as shown below.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate variance of  sampling distributions</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(ms,<span class="dv">1</span>,var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##       mean     median 
## 0.09868766 0.13808784</code></pre>
<p>We see that the variance for the sample median is much higher.This shows that the sample mean, rather than the sample median is the minimum variance estimator of the population mean.</p>
</section>
</section>
<section id="confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h3>
<p>We have an estimator to obtain a point estimate for the Number of tanks. We also want to construct a confidence interval around this estimate with some significance level( <span class="math inline">\(\alpha = 5\)</span>%)</p>
<p>The lower bound for the Number of tanks is given by <span class="math inline">\(m\)</span>, the maximum number we observe, as it is certain that the enemy has at least <span class="math inline">\(m\)</span> tanks.</p>
<p>We have to establish an upper bound for the 95% ( <span class="math inline">\(1 - \alpha\)</span>) confidence interval.</p>
<p>To get to this we must answer the following question.</p>
<p><strong>Given a collection of <span class="math inline">\(k\)</span> integers, <span class="math inline">\(n_1,n_2,\dots,n_k\)</span> sampled independently and uniformly (with replacement) from the range <span class="math inline">\(1\)</span> to <span class="math inline">\(N\)</span>, what is the probability that the maximum value we observe i.e.&nbsp;<span class="math inline">\(Max(n_1,\dots,n_k)\)</span> is <span class="math inline">\(\geq\)</span> m ?</strong></p>
<p>The probability of observing a maximum value less than or equal to <span class="math inline">\(m\)</span>, or the cumulative probability mass function is given by <span class="math inline">\(P [Max \leq m ] =(\frac{m}{N})^k\)</span> i.e.&nbsp;all tanks observed should have a number less than <span class="math inline">\(m\)</span></p>
<p>The probability of observing a maximum value greater than <span class="math inline">\(m\)</span> is given by:</p>
<p><span class="math display">\[ P [Max \gt m ]  = 1 - (\frac{m}{N})^k \]</span></p>
<p>We can determine the upper bound of the confidence interval by setting above value equal to <span class="math inline">\(1 - \alpha\)</span> and solving for <span class="math inline">\(N\)</span> which gives:</p>
<p><span class="math display">\[ N_{1 - \alpha} = \frac{m}{(\alpha)^\frac{1}{k}}   \]</span></p>
<p>We can conduct an experiment to validate the results as shown below. Assume there are a hundred different spies who each observe some tanks and record the serial numbers. From each spy’s observation we can estimate the total number of tanks and construct a confidence interval around each estimate.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># True number of tanks</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of tanks observed</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume a 1000 different spies observe tanks and record the maximum number they observe.</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="do">##Function to simulate k tanks observed by a spy</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span><span class="cf">function</span>(N,k){<span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>N),k,<span class="at">replace =</span> <span class="cn">TRUE</span>)}</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Record the tank numbers observed by a 1000 spies</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,<span class="fu">f</span>(N,k))  </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Get maximum observed by each spy</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>max_ <span class="ot">&lt;-</span> <span class="fu">apply</span>(obs,<span class="dv">2</span>,max)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Get estimate of Number of tanks</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>N_hat <span class="ot">=</span> max_<span class="sc">*</span>(k<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span>k <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(N_hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-6-1.png" width="672"></p>
<p>Let us extract the maximum number observed by the first spy and the estimated number of tanks based on this observation.</p>
<pre><code>## The tank numbers observed by the first spy are : 324 167 129 418</code></pre>
<pre><code>## The maximum tank number observed by the first spy is 418</code></pre>
<pre><code>## The estimated number of total tanks based on this number is 521.5</code></pre>
<p>Now we can also calculate a 95% confidence interval around each of these estimates.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>N_95 <span class="ot">&lt;-</span> <span class="fu">floor</span>((max_)<span class="sc">/</span>(alpha)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="st">'Lower_Bound'</span><span class="ot">=</span> max_,<span class="st">'Upper_Bound'</span><span class="ot">=</span>N_95)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The confidence interval around the estimate from the first spy’s observations is given by</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ci[,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Lower_Bound Upper_Bound 
##         418         883</code></pre>
<p>By definition, if we calculate a 95% confidence interval around an estimate, 95% of calculated confidence intervals should contain the true value.</p>
<p>We can calculate the number of confidence intervals containing the true value of 500.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>bool <span class="ot">=</span> ci[<span class="dv">1</span>,] <span class="sc">&lt;=</span> N <span class="sc">&amp;</span> ci[<span class="dv">2</span>,]<span class="sc">&gt;=</span> N</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(bool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [1] 951</code></pre>
<p>This shows that approximately <span class="math inline">\(1 - \alpha = 0.95\)</span>, or 95% of confidence intervals contain the true value which is consistent with the frequentist definition of confidence intervals.</p>
<p>We can plot the estimate and confidence intervals as shown below.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct a full data frame for plotting</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>(<span class="fu">ncol</span>(ci))),N_hat,<span class="fu">t</span>(ci)))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"N"</span>,<span class="st">"Estimate"</span>,<span class="st">"Lower_Bound"</span>,<span class="st">"Upper_Bound"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>N,<span class="at">y =</span> Estimate)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>Lower_Bound, <span class="at">ymax =</span> Upper_Bound))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-11-1.png" width="672"></p>
<section id="p--value" class="level4">
<h4 class="anchored" data-anchor-id="p--value">P- value</h4>
<p>We have defined a confidence interval above. but how does it relate to a p-value?</p>
<p>Consider that there are 500(N=500) tanks the Germans had in battle. The probability mass function of the maximum serial number observed <span class="math inline">\(m\)</span>, for <span class="math inline">\(k\)</span> observation given <span class="math inline">\(N\)</span> tanks exist is given by</p>
<p><span class="math display">\[  P [Max = m ] =  \begin{cases}
    (\frac{m}{N})^k - (\frac{m-1}{N})^k,&amp; \text{if }  m\leq N\\
    0,              &amp; \text{otherwise}
\end{cases}\]</span>`</p>
<p>This can be plotted as shown below.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>pmf <span class="ot">&lt;-</span> <span class="cf">function</span>(m,N,k){</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>((m<span class="sc">/</span>N)<span class="sc">^</span>k <span class="sc">-</span> ((m<span class="dv">-1</span>)<span class="sc">/</span>N)<span class="sc">^</span>k)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>m_ <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>N)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>pmf_ <span class="ot">&lt;-</span> <span class="fu">sapply</span>(m_,pmf,N,k)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m_,pmf_,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">xlab =</span> <span class="st">"Max"</span>, <span class="at">ylab=</span><span class="st">"probability density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-12-1.png" width="672"></p>
<p>Now we have to define a rejection region. If the maximum <span class="math inline">\(m\)</span> we observe is within this rejection region, we reject the hypothesized value of <span class="math inline">\(N\)</span>.</p>
<p>The confidence interval we calculated corresponds to defining a rejection region on the left tail of the distribution.</p>
<p>Assuming a <span class="math inline">\(\alpha (=5 \%)\)</span> significance level, this rejection region can be determined by calculating the value of <span class="math inline">\(m\)</span> where the cumulative mass function has a value of <span class="math inline">\(\alpha\)</span>.</p>
<p><span class="math display">\[ (\frac{m'}{k})^N = \alpha \]</span></p>
<p><span class="math display">\[ m' = \alpha^{\frac{1}{k}}N  \]</span></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>rejection_region_max <span class="ot">=</span> <span class="fu">floor</span>(alpha<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> N)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>rejection_region_max</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [1] 236</code></pre>
<p>The rejection region is given by the shaded area in the figure below. <img src="./staticunnamed-chunk-14-1.png" width="672"></p>
<p>So if the maximum serial number we observe <span class="math inline">\(m\)</span> is less than 236, we can reject the null hypothesis, that the actual number of tanks is 500.</p>
<p>As noted in the earlier section, the maximum tank number observed by the first spy is 418. So, we do not reject the null hypothesis that the actual number of tanks is 500. Now, what are the possible values of N, where we would reject the null hypothesis given we observed a maximum of 418 ?</p>
<p>Well,what about N = 417 ? If there were only 417 tanks in total, we would not observe a tank with a serial number of 418, so we can rule out 417 as well as all values of N between 1 and 417</p>
<p>Then, what bout N = 883. We would reject this null hypothesis if we observe a maximum tank number less than:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">round</span>(alpha<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> <span class="dv">883</span>,<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 417.54</code></pre>
<p>Given the spy observe a tank number of 418, we don’t reject this null hypothesis either.</p>
<p>What about N =884,We would reject this null hypothesis if we observe a maximum tank number less than:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">round</span>(alpha<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> <span class="dv">884</span>,<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 418.02</code></pre>
<p>OK - So we did observe a tank number less than 418.02, so we reject this null hypothesis. We do the same for all hypothesized values of N greater than 884.</p>
<p>So the range of hypothesized values of N for which we don’t reject the null hypothesis is [418,883]. This is exactly the confidence interval computed above!</p>
</section>
<section id="significance-level" class="level4">
<h4 class="anchored" data-anchor-id="significance-level">Significance Level</h4>
<p>For both confidence intervals and p values, I specified a significance level <span class="math inline">\(\alpha  = 5 \%\)</span>. This is simply the likelihood of rejecting a null hypothesis when it is true i.e.&nbsp;the probability of a false positive.</p>
<p>Given the distribution of <span class="math inline">\(m\)</span> for a hypothesized value of <span class="math inline">\(N\)</span> in Figure X, there is still an <span class="math inline">\(\alpha\)</span>% chance that we will observe a value of <span class="math inline">\(m\)</span> in the rejection region and incorrectly reject the null hypothesis.</p>
<p>Similarly, there is an <span class="math inline">\(\alpha  = 5\)</span>% chance that the true value of <span class="math inline">\(N\)</span> falls outside the <span class="math inline">\(1 -\alpha = 95\)</span>% confidence interval.</p>
<p>Now you might wonder what is the probability of a false negative. This is related to the power of a statistical test which I will not explore in this blog. The references at the end of the blog will be useful if you want to explore this idea.</p>
</section>
</section>
<section id="a-more-conservative-confidence-interval" class="level3">
<h3 class="anchored" data-anchor-id="a-more-conservative-confidence-interval">A more conservative confidence interval</h3>
<p>Now let us assume we want to be a bit more risk averse about underestimating the number of tanks. This may be because the war is in its early stage when German manufacturing capabilities had not been severely depleted by Allied bombing.</p>
<p>If the maximum we observe is <span class="math inline">\(m\)</span>, we want the confidence interval to be conservative and be defined by a range starting at <span class="math inline">\(m+i\)</span>, where <span class="math inline">\(i\)</span> is some whole number, rather than <span class="math inline">\(m\)</span>.</p>
<p>In other words, we want the 95% confidence interval to capture a range more like the upper image rather than the lower image.</p>
<p><img src="./staticunnamed-chunk-17-1.png" width="672"></p>
<p>First, we want to first establish the lower bound of this new confidence interval.</p>
<p>As established earlier, the probability of observing a maximum value greater than <span class="math inline">\(m\)</span> is given by:</p>
<p><span class="math display">\[ P \big( Max \gt m \big)  = 1 - (\frac{m}{N})^k \]</span></p>
<p>By setting above value equal to <span class="math inline">\(\alpha\)</span> and solving for <span class="math inline">\(N\)</span> gives:</p>
<p><span class="math display">\[ N_{\alpha} = \frac{m}{(1 -\alpha)^\frac{1}{k}}   \]</span></p>
<p>This gives the lower bound of the confidence interval.</p>
<p>Now, what is the upper bound of the confidence interval ? The upper bound turns out to be <span class="math inline">\(\infty\)</span>.</p>
<p>We can again conduct an experiment to validate the results as shown below.</p>
<p>We can calculate a new 95% confidence interval around each estimate as shown below.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>N_05 <span class="ot">&lt;-</span> <span class="fu">ceiling</span>((max_)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span> alpha)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>ci_desired <span class="ot">&lt;-</span> <span class="fu">rbind</span>(N_05,<span class="fu">rep</span>(<span class="cn">Inf</span>,N))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Calculate number of confidence intervals containing the true value of 10000.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>bool <span class="ot">=</span> ci_desired[<span class="dv">1</span>,] <span class="sc">&lt;=</span> N <span class="sc">&amp;</span> ci_desired[<span class="dv">2</span>,]<span class="sc">&gt;=</span> N</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(bool)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [1] 943</code></pre>
<p>This shows that approximately <span class="math inline">\(1 - \alpha = 0.95\)</span>, or 95% of confidence intervals contain the true value which is again consistent with the frequentist definition of confidence intervals.</p>
<p>The confidence interval around estimated number of tanks observed by the first spy is:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"["</span>,ci_desired[<span class="dv">1</span>,<span class="dv">1</span>],<span class="st">","</span>,<span class="fu">round</span>(ci_desired[<span class="dv">2</span>,<span class="dv">1</span>],<span class="dv">0</span>),<span class="st">"]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [ 424 , Inf ]</code></pre>
<section id="p-value" class="level4">
<h4 class="anchored" data-anchor-id="p-value">P-value</h4>
<p>How does this new confidence interval relate to p-values.</p>
<p>This new confidence interval we define simply corresponds to defining a rejection region on the right tail of the distribution.</p>
<p>Assuming a <span class="math inline">\(\alpha (=5 \%)\)</span> significance level, this new rejection region can be determined by calculating the value of <span class="math inline">\(m\)</span> where the cumulative probability mass function has a value of <span class="math inline">\(1 - \alpha\)</span></p>
<p><span class="math display">\[ (\frac{m'}{N})^k =  1 -\alpha \]</span> <span class="math display">\[ m' = (1 -\alpha)^{\frac{1}{k}}N  \]</span> Let our null hypothesis be that the number of tanks is 500, then the rejection region is given by the shaded region in the figure below.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>rejection_region_min <span class="ot">=</span> (<span class="dv">1</span><span class="sc">-</span>alpha)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> N</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>rejection_region_min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [1] 493.6293</code></pre>
<p><img src="./staticunnamed-chunk-22-1.png" width="672"></p>
<p>So if the maximum serial number we observe <span class="math inline">\(m\)</span> is greater than 493, we can reject the null hypothesis <span class="math inline">\(H0: N = 500\)</span></p>
<p>As noted in earlier section, the maximum tank number observed by the first spy is 418. So, we do not reject the hypothesis that the actual number of tanks is 500. Now what are the possible values of N, where we would reject the null hypothesis given we observed a maximum of 418 ?</p>
<p>What about N = 423. We would reject this null hypothesis if we observe a maximum tank number greater than :</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>((<span class="dv">1</span> <span class="sc">-</span> alpha)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> <span class="dv">423</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 417.6104</code></pre>
<p>Given the maximum we observed is 418, we reject this null hypothesis.</p>
<p>What about N = 424. We would reject this null hypothesis if we observe a maximum tank number greater than :</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>((<span class="dv">1</span> <span class="sc">-</span> alpha)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> <span class="dv">424</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 418.5976</code></pre>
<p>Given the spy observed a tank number of 418, we don’t reject this null hypothesis either.</p>
<p>What about N =10000, We would reject this null hypothesis if we observe a maximum tank number greater than :</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>((<span class="dv">1</span> <span class="sc">-</span> alpha)<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span>k) <span class="sc">*</span> <span class="dv">10000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 9872.585</code></pre>
<p>Given the spy observe a tank number of 418, we don’t reject this null hypothesis either.It follows that we won’t reject the null hypothesis for any value of N greater than 424.</p>
<p>So the range of hypothesized values of N for which we don’t reject the null hypothesis is <span class="math inline">\(\[424,\infty\]\)</span>. This is exactly the confidence interval computed above.</p>
</section>
</section>
<section id="limitations-of-the-frequentist-approach" class="level3">
<h3 class="anchored" data-anchor-id="limitations-of-the-frequentist-approach">Limitations of the Frequentist Approach</h3>
<p>Not withstanding the fact that the definition of confidence intervals is confusing <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, we see that the two ways of computing the confidence interval can give answers of wildly varying utility. There is also no technical reason why one confidence interval is preferable compared to the other.</p>
</section>
</section>
<section id="the-bayesian-approach" class="level2">
<h2 class="anchored" data-anchor-id="the-bayesian-approach">The Bayesian Approach</h2>
<p>An alternative to the Frequentist Approach we covered above is a Bayesian approach <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. Just like we calculated confidence intervals, we can can calculate a credible interval for the number of tanks the enemy has, given the tank serial numbers observed by a spy.</p>
<p>Although this simple enough problem to solve analytically <a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, a more general approach is to solve this using a Markov Chain Monte Carlo sampler. This can be done by using the software package <code>JAGS</code> and the R interface to JAGS <code>rjags</code>.</p>
<p>Let us consider the tanks observed by the first spy.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> obs[ ,<span class="dv">1</span>]</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## [1] 324 167 129 418</code></pre>
<p>Fo this analysis, we will use a set of utility functions available as part of the book <code>Doing Bayesian Data Analysis</code> by John Kruschke.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"utilities.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Loading required package: coda</code></pre>
<pre><code>## Linked to JAGS 4.3.1</code></pre>
<pre><code>## Loaded modules: basemod,bugs</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(rjags)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(coda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>First, the data to be analyzed is packaged into a list to be shipped to the JAGS sampler.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Put data into a list</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>dataList <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> y, <span class="co"># Observations</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Ntotal =</span> <span class="fu">length</span>(y), <span class="co"># No of observations</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_max =</span> <span class="fu">max</span>(y) <span class="co"># Maximum tank number observed</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>To complete a Bayesian analysis, in addition to the likelihood function we covered at the beginning of this post, we also need to define a prior.</p>
<p>The prior should be informed by our understanding of the problem and the domain.</p>
<p>To begin with, given our estimates of German production capacity towards the end of the war, we might know that the Germans have no more than 1000 tanks. Given we have no further information, we will assume a uniform prior i.e.&nbsp;any number of tanks between the maximum observed by the spy and 1000 is equally likely.<br>
We can specify this models as shown below.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define the model</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rjags)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>model0 <span class="ot">=</span> <span class="st">"</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="st">model {</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="st">  for ( i in 1:Ntotal ) {</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="st">    y[i] ~ dunif(0,N) #Likelihhod</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="st">  N ~ dunif( y_max, 1000) #Prior</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="st">}"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If this were the beginning of the war, we would think the Germans have a much higher production capacity. We would revise the top end of our prior estimate from 1000 to 10000.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">=</span> <span class="st">"</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="st">model {</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="st">  for ( i in 1:Ntotal ) {</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="st">    y[i] ~ dunif(0,N) #Likelihhod</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="st">  N ~ dunif( y_max, 10000) #Prior</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="st">}"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>At the end of the war, we might even have more information on the German production capacity that allows us to have a more precise prior. For e.g.&nbsp;we might have a prior belief think the number of tanks the enemy has is characterized by the following distribution.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">rgamma</span>(<span class="dv">1000</span>,<span class="dv">25</span>,<span class="fl">0.05</span>),<span class="at">main =</span> <span class="st">" Prior belief at end of war"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-32-1.png" width="672"></p>
<p>We can define a model with this more precise prior as shown below.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define the model</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rjags)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">=</span> <span class="st">"</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="st">model {</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="st">  for ( i in 1:Ntotal ) {</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="st">    y[i] ~ dunif(0,N) #Likelihhod</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="st">  }</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="st">  N ~ dgamma(25,0.05) #Prior</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="st">}"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="run-models" class="level2">
<h2 class="anchored" data-anchor-id="run-models">Run Models</h2>
<p>For each of these priors, we can now run MCMC samplers to infer what the posterior distribution of tanks is given the tank numbers observed by a spy.</p>
<p>When running the chains, it is typical to specify a burn in period so as to discard the few initial values before the chain has settled on the true posterior. The number of steps to be taken to tune/adapt the samplers can also be specified.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>parameters <span class="ot">=</span> <span class="fu">c</span>( <span class="st">"N"</span>)     <span class="co"># The parameters to be monitored</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>adaptSteps <span class="ot">=</span>  <span class="dv">500</span>        <span class="co"># Number of steps to adapt/tune the samplers</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>burnInSteps <span class="ot">=</span> <span class="dv">500</span>        <span class="co"># Number of steps to burn-in the chains</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>nChains <span class="ot">=</span> <span class="dv">4</span>              <span class="co"># nChains should be 2 or more for diagnostics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The three models can now be run and analyzed.</p>
<section id="model-0---end-of-war-with-limited-intelligence" class="level3">
<h3 class="anchored" data-anchor-id="model-0---end-of-war-with-limited-intelligence">Model 0 - End of War with limited intelligence</h3>
<div class="sourceCode" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the chains:</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>jagsModel0 <span class="ot">=</span> <span class="fu">jags.model</span>(<span class="at">file=</span> <span class="fu">textConnection</span>(model0) , <span class="at">data=</span>dataList , </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">n.chains=</span> nChains , <span class="at">n.adapt=</span> adaptSteps )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Compiling model graph
##    Resolving undeclared variables
##    Allocating nodes
## Graph information:
##    Observed stochastic nodes: 4
##    Unobserved stochastic nodes: 1
##    Total graph size: 9
## 
## Initializing model</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Burn in to stabilize the chains</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">update</span>( jagsModel0 , <span class="at">n.iter=</span> burnInSteps )</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run chains to estimate posterior distribution</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>codaSamples0 <span class="ot">=</span> <span class="fu">coda.samples</span>( jagsModel0 , <span class="at">variable.names=</span><span class="fu">c</span>(<span class="st">"N"</span>) ,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">n.iter=</span><span class="dv">2500</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Note that running the diagnostics on the sampled chains is an important part of the Bayesian analysis. See this <a href="https://www.govindgnair.com/post/introduction-to-bayesian-methods/">post</a> to learn more about diagnostics.</p>
<p>The posterior distribution resulting from this model can now be analyzed.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>( <span class="at">mar=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">0.5</span>,<span class="fl">2.5</span>,<span class="fl">0.5</span>) , <span class="at">mgp=</span><span class="fu">c</span>(<span class="fl">2.25</span>,<span class="fl">0.7</span>,<span class="dv">0</span>) )</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPost</span>( codaSamples0[,<span class="st">"N"</span>] , <span class="at">main=</span><span class="st">"N"</span> , <span class="at">xlab=</span><span class="st">"N"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-36-1.png" width="672"></p>
<pre><code>##        ESS     mean  median   mode hdiMass   hdiLow  hdiHigh
## N 2036.402 556.6577 512.555 446.73    0.95 418.0032 841.3058</code></pre>
<p>We see that the bayesian inference procedure gives us a credible interval comprising the values with the highest density. Rather than a confidence interval where the information we have is limited to whether the true value lies inside or outside the confidence interval, this credible interval gives the posterior probability of the parameter value.</p>
<p>We can also estimate the probability that the actual Number of tanks is between any two values. For example, the probability that the number of tanks is between 418 and 500 is given by.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> <span class="fu">unlist</span>(codaSamples0)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>prob_419_500 <span class="ot">&lt;-</span> <span class="fu">sum</span>((posterior<span class="sc">&gt;=</span> <span class="dv">419</span> <span class="sc">&amp;</span> posterior <span class="sc">&lt;=</span> <span class="dv">500</span>))<span class="sc">/</span><span class="fu">length</span>(posterior)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The probability that the number of tanks is between 419 and 500 is:"</span>,prob_419_500)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## The probability that the number of tanks is between 419 and 500 is: 0.4487</code></pre>
</section>
<section id="model-1---beginning-of-war-with-limited-intelligence" class="level3">
<h3 class="anchored" data-anchor-id="model-1---beginning-of-war-with-limited-intelligence">Model 1 - Beginning of war with limited intelligence</h3>
<p>Run chains for Model 1.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the chains:</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>jagsModel1 <span class="ot">=</span> <span class="fu">jags.model</span>(<span class="at">file=</span> <span class="fu">textConnection</span>(model1) , <span class="at">data=</span>dataList , </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">n.chains=</span> nChains , <span class="at">n.adapt=</span> adaptSteps )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Compiling model graph
##    Resolving undeclared variables
##    Allocating nodes
## Graph information:
##    Observed stochastic nodes: 4
##    Unobserved stochastic nodes: 1
##    Total graph size: 9
## 
## Initializing model</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Burn in to stabilize the chains</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">update</span>( jagsModel1 , <span class="at">n.iter=</span> burnInSteps )</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run chains to estimate posterior distribution</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>codaSamples1 <span class="ot">=</span> <span class="fu">coda.samples</span>( jagsModel1 , <span class="at">variable.names=</span><span class="fu">c</span>(<span class="st">"N"</span>) ,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">n.iter=</span><span class="dv">2500</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The posterior distribution resulting from this model can now be analyzed.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>( <span class="at">mar=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">1.5</span>,<span class="fl">2.5</span>,<span class="fl">0.5</span>) , <span class="at">mgp=</span><span class="fu">c</span>(<span class="fl">2.25</span>,<span class="fl">0.7</span>,<span class="dv">0</span>) )</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPost</span>( codaSamples1[,<span class="st">"N"</span>] , <span class="at">main=</span><span class="st">"N"</span> , <span class="at">xlab=</span><span class="st">"N"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">2000</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-39-1.png" width="672"></p>
<pre><code>##        ESS     mean   median     mode hdiMass   hdiLow  hdiHigh
## N 241.2465 643.6212 527.8942 454.1553    0.95 418.0154 1213.298</code></pre>
<p>In this case, we see that the posterior distribution is much wider than in Model 0.</p>
<p>This is fully expected given we are at the beginning of the war where German production capabilities are fully intact. Even though the highest tank number we observed was 418, we expect the enemy to have a much larger number of tanks then towards the end of the war.</p>
</section>
<section id="model-2---end-of-war-with-superior-intelligence" class="level3">
<h3 class="anchored" data-anchor-id="model-2---end-of-war-with-superior-intelligence">Model 2 - End of war with superior intelligence</h3>
<p>Run chains for Model 2.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the chains:</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>jagsModel2 <span class="ot">=</span> <span class="fu">jags.model</span>(<span class="at">file=</span> <span class="fu">textConnection</span>(model2) , <span class="at">data=</span>dataList , </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">n.chains=</span> nChains , <span class="at">n.adapt=</span> adaptSteps )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Compiling model graph
##    Resolving undeclared variables
##    Allocating nodes
## Graph information:
##    Observed stochastic nodes: 4
##    Unobserved stochastic nodes: 1
##    Total graph size: 9
## 
## Initializing model</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Burn in to stabilize the chains</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">update</span>( jagsModel2 , <span class="at">n.iter=</span> burnInSteps )</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Run chains to estimate posterior distribution</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>codaSamples2 <span class="ot">=</span> <span class="fu">coda.samples</span>( jagsModel2 , <span class="at">variable.names=</span><span class="fu">c</span>(<span class="st">"N"</span>) ,</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">n.iter=</span><span class="dv">2500</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The posterior distribution resulting from this model can now be analyzed.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>( <span class="at">mar=</span><span class="fu">c</span>(<span class="fl">3.5</span>,<span class="fl">0.5</span>,<span class="fl">2.5</span>,<span class="fl">0.5</span>) , <span class="at">mgp=</span><span class="fu">c</span>(<span class="fl">2.25</span>,<span class="fl">0.7</span>,<span class="dv">0</span>) )</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPost</span>( codaSamples2[,<span class="st">"N"</span>] , <span class="at">main=</span><span class="st">"N"</span> , <span class="at">xlab=</span><span class="st">"N"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./staticunnamed-chunk-41-1.png" width="672"></p>
<pre><code>##        ESS     mean   median     mode hdiMass   hdiLow  hdiHigh
## N 2796.591 495.5214 480.9062 437.8477    0.95 418.0296 618.4802</code></pre>
<p>Given the improved intelligence we have a the end of the war, we see that we can arrive at a much narrower posterior and hence a more confident estimate.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>We have used frequentist and statistical inference to solve the German Tank problem. In this particular problem, the benefits of the Bayesian approach are evident. Besides being more intuitive, it also obviates the need for concepts like rejection regions and p-values.</p>
<p>The code underlying this blog post is available <a href="https://github.com/govindgnair23/German-Tank-Problem">here</a>.</p>
</section>
<section id="references-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="references-and-further-reading">References and Further Reading</h2>
<ol type="a">
<li><a href="https://www.amazon.com/Doing-Bayesian-Data-Analysis-Tutorial/dp/0124058884">Doing Bayesian Data Analysis : A Tutorial with R, JAGS, and Stan</a> <br></li>
<li><a href="https://www.amazon.com/Bernoullis-Fallacy-Statistical-Illogic-Science/dp/0231199945">Bernoulli’s Fallacy: Statistical Illogic and the Crisis of Modern Science</a> <br></li>
<li>https://www.isaacslavitt.com/posts/german-tank-problem-with-pymc-and-pystan/ <br></li>
<li>https://www.mjandrews.org/blog/germantank/ <d></d></li>
</ol>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>https://en.wikipedia.org/wiki/German_tank_problem<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>https://www.youtube.com/watch?v=quV-MCB8Ozs<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>https://en.wikipedia.org/wiki/Variance#Population_variance_and_sample_variance<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>http://jakevdp.github.io/blog/2014/06/12/frequentism-and-bayesianism-3-confidence-credibility/<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>https://www.govindgnair.com/post/introduction-to-bayesian-methods/<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>https://www.mjandrews.org/blog/germantank/<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2024, Govind G Nair</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>